<a href="https://colab.research.google.com/github/luisafelixx/Fairness_Diabetes/blob/main/Sele%C3%A7%C3%A3o_Atributos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv('2015.csv')

In [ ]:
pd.set_option('display.max_columns', None)

In [ ]:
data.shape

(441456, 330)

In [ ]:
data.head()

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENUM,PVTRESD1,COLGHOUS,STATERES,CELLFON3,LADULT,NUMADULT,NUMMEN,NUMWOMEN,CTELNUM1,CELLFON2,CADULT,PVTRESD2,CCLGHOUS,CSTATE,LANDLINE,HHADULT,GENHLTH,PHYSHLTH,MENTHLTH,POORHLTH,HLTHPLN1,PERSDOC2,MEDCOST,CHECKUP1,BPHIGH4,BPMEDS,BLOODCHO,CHOLCHK,TOLDHI2,CVDINFR4,CVDCRHD4,CVDSTRK3,ASTHMA3,ASTHNOW,CHCSCNCR,CHCOCNCR,CHCCOPD1,HAVARTH3,ADDEPEV2,CHCKIDNY,DIABETE3,DIABAGE2,SEX,MARITAL,EDUCA,RENTHOM1,NUMHHOL2,NUMPHON2,CPDEMO1,VETERAN3,EMPLOY1,CHILDREN,INCOME2,INTERNET,WEIGHT2,HEIGHT3,PREGNANT,QLACTLM2,USEEQUIP,BLIND,DECIDE,DIFFWALK,DIFFDRES,DIFFALON,SMOKE100,SMOKDAY2,STOPSMK2,LASTSMK2,USENOW3,ALCDAY5,AVEDRNK2,DRNK3GE5,MAXDRNKS,FRUITJU1,FRUIT1,FVBEANS,FVGREEN,FVORANG,VEGETAB1,EXERANY2,EXRACT11,EXEROFT1,EXERHMM1,EXRACT21,EXEROFT2,EXERHMM2,STRENGTH,LMTJOIN3,ARTHDIS2,ARTHSOCL,JOINPAIN,SEATBELT,FLUSHOT6,FLSHTMY2,IMFVPLAC,PNEUVAC3,HIVTST6,HIVTSTD3,WHRTST10,PDIABTST,PREDIAB1,INSULIN,BLDSUGAR,FEETCHK2,DOCTDIAB,CHKHEMO3,FEETCHK,EYEEXAM,DIABEYE,DIABEDU,PAINACT2,QLMENTL2,QLSTRES2,QLHLTH2,CAREGIV1,CRGVREL1,CRGVLNG1,CRGVHRS1,CRGVPRB1,CRGVPERS,CRGVHOUS,CRGVMST2,CRGVEXPT,VIDFCLT2,VIREDIF3,VIPRFVS2,VINOCRE2,VIEYEXM2,VIINSUR2,VICTRCT4,VIGLUMA2,VIMACDG2,CIMEMLOS,CDHOUSE,CDASSIST,CDHELP,CDSOCIAL,CDDISCUS,WTCHSALT,LONGWTCH,DRADVISE,ASTHMAGE,ASATTACK,ASERVIST,ASDRVIST,ASRCHKUP,ASACTLIM,ASYMPTOM,ASNOSLEP,ASTHMED3,ASINHALR,HAREHAB1,STREHAB1,CVDASPRN,ASPUNSAF,RLIVPAIN,RDUCHART,RDUCSTRK,ARTTODAY,ARTHWGT,ARTHEXER,ARTHEDU,TETANUS,HPVADVC2,HPVADSHT,SHINGLE2,HADMAM,HOWLONG,HADPAP2,LASTPAP2,HPVTEST,HPLSTTST,HADHYST2,PROFEXAM,LENGEXAM,BLDSTOOL,LSTBLDS3,HADSIGM3,HADSGCO1,LASTSIG3,PCPSAAD2,PCPSADI1,PCPSARE1,PSATEST1,PSATIME,PCPSARS1,PCPSADE1,PCDMDECN,SCNTMNY1,SCNTMEL1,SCNTPAID,SCNTWRK1,SCNTLPAD,SCNTLWK1,SXORIENT,TRNSGNDR,RCSGENDR,RCSRLTN2,CASTHDX2,CASTHNO2,EMTSUPRT,LSATISFY,ADPLEASR,ADDOWN,ADSLEEP,ADENERGY,ADEAT1,ADFAIL,ADTHINK,ADMOVE,MISTMNT,ADANXEV,QSTVER,QSTLANG,EXACTOT1,EXACTOT2,MSCODE,_STSTR,_STRWT,_RAWRAKE,_WT2RAKE,_CHISPNC,_CRACE1,_CPRACE,_CLLCPWT,_DUALUSE,_DUALCOR,_LLCPWT,_RFHLTH,_HCVU651,_RFHYPE5,_CHOLCHK,_RFCHOL,_MICHD,_LTASTH1,_CASTHM1,_ASTHMS1,_DRDXAR1,_PRACE1,_MRACE1,_HISPANC,_RACE,_RACEG21,_RACEGR3,_RACE_G1,_AGEG5YR,_AGE65YR,_AGE80,_AGE_G,HTIN4,HTM4,WTKG3,_BMI5,_BMI5CAT,_RFBMI5,_CHLDCNT,_EDUCAG,_INCOMG,_SMOKER3,_RFSMOK3,DRNKANY5,DROCDY3_,_RFBING5,_DRNKWEK,_RFDRHV5,FTJUDA1_,FRUTDA1_,BEANDAY_,GRENDAY_,ORNGDAY_,VEGEDA1_,_MISFRTN,_MISVEGN,_FRTRESP,_VEGRESP,_FRUTSUM,_VEGESUM,_FRTLT1,_VEGLT1,_FRT16,_VEG23,_FRUITEX,_VEGETEX,_TOTINDA,METVL11_,METVL21_,MAXVO2_,FC60_,ACTIN11_,ACTIN21_,PADUR1_,PADUR2_,PAFREQ1_,PAFREQ2_,_MINAC11,_MINAC21,STRFREQ_,PAMISS1_,PAMIN11_,PAMIN21_,PA1MIN_,PAVIG11_,PAVIG21_,PA1VIGM_,_PACAT1,_PAINDX1,_PA150R2,_PA300R2,_PA30021,_PASTRNG,_PAREC1,_PASTAE1,_LMTACT1,_LMTWRK1,_LMTSCL1,_RFSEAT2,_RFSEAT3,_FLSHOT6,_PNEUMO2,_AIDTST3
0,1.0,1.0,b'01292015',b'01',b'29',b'2015',1200.0,2.015000e+09,2.015000e+09,1.0,1.0,NaN,1.0,2.0,NaN,3.0,1.000000e+00,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,15.0,18.0,10.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,3.0,NaN,2.0,1.0,4.0,1.0,2.0,NaN,1.0,2.0,8.0,88.0,3.0,2.0,280.0,510.0,NaN,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,3.0,NaN,2.0,3.0,888.0,NaN,NaN,NaN,305.0,310.0,320.0,310.0,305.0,101.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,888.0,1.0,1.0,1.0,6.0,1.0,1.0,112014.0,1.0,1.0,1.0,NaN,NaN,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,b'',b'',3.0,11011.0,28.78156,3.0,86.344681,NaN,NaN,NaN,NaN,1.0,0.614125,341.384853,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,9.0,1.0,63.0,5.0,70.0,178.0,12701.0,4018.0,4.0,2.0,1.0,2.0,2.0,3.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,1.700000e+01,33.0,6.700000e+01,33.0,17.0,100.0,5.397605e-79,5.397605e-79,1.000000e+00,1.000000e+00,50.0,217.0,2.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,2.0,NaN,NaN,2469.0,423.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.397605e-79,5.397605e-79,NaN,NaN,NaN,NaN,NaN,NaN,4.0,2.0,3.0,3.0,2.0,2.0,4.0,2.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,1.0
1,1.0,1.0,b'01202015',b'01',b'20',b'2015',1100.0,2.015000e+09,2.015000e+09,1.0,1.0,NaN,1.0,2.0,NaN,1.0,5.397605e-79,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,88.0,88.0,NaN,2.0,1.0,1.0,4.0,3.0,NaN,1.0,4.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,3.0,NaN,2.0,2.0,6.0,1.0,2.0,NaN,2.0,2.0,3.0,88.0,1.0,1.0,165.0,508.0,NaN,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,NaN,3.0,888.0,NaN,NaN,NaN,302.0,305.0,302.0,202.0,202.0,304.0,1.0,64.0,212.0,100.0,69.0,212.0,100.0,888.0,NaN,NaN,NaN,NaN,3.0,2.0,NaN,NaN,2.0,2.0,NaN,NaN,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,5.0,5.0,NaN,5.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',1.0,2.0,NaN,NaN,2.0,60.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,b'',b'',5.0,11011.0,28.78156,1.0,28.781560,NaN,NaN,NaN,NaN,9.0,NaN,108.060903,1.0,2.0,1.0,2.0,1.0,2.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,7.0,1.0,52.0,4.0,68.0,173.0,7484.0,2509.0,3.0,2.0,1.0,4.0,1.0,1.0,2.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,7.000000e+00,17.0,7.000000e+00,29.0,29.0,13.0,5.397605e-79,5.397605e-79,1.000000e+00,1.000000e+00,24.0,78.0,2.0,2.0,1.0,1.0,5.397605e-79,5.397605e-79,1.0,35.0,5.397605e-79,2876.0,493.0,1.0,5.397605e-79,60.0,60.0,2800.0,2800.0,168.0,5.397605e-79,5.397605e-79,5.397605e-79,168.0,5.397605e-79,168.0,5.397605e-79,5.397605e-79,5.397605e-79,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,4.0,2.0,2.0,NaN,NaN,2.0
2,1.0,1.0,b'02012015',b'02',b'01',b'2015',1200.0,2.015000e+09,2.015000e+09,1.0,1.0,NaN,1.0,2.0,NaN,2.0,1.000000e+00,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,15.0,88.0,88.0,1.0,2.0,2.0,1.0,3.0,NaN,1.0,1.0,1.0,7.0,2.0,1.0,2.0,NaN,2.0,1.0,2.0,1.0,2.0,2.0,3.0,NaN,2.0,2.0,4.0,1.0,2.0,NaN,1.0,2.0,7.0,88.0,99.0,2.0,158.0,511.0,NaN,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,b'',b'',5.0,11011.0,28.78156,2.0,57.563120,NaN,NaN,NaN,NaN,1.0,0.614125,255.264797,2.0,9.0,1.0,1.0,2.0,NaN,1.0,1.0,3.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,11.0,2.0,71.0,6.0,71.0,180.0,7167.0,2204.0,2.0,1.0,1.0,2.0,9.0,9.0,9.0,9.0,9.000000e+02,9.0,9.990000e+04,9.0,NaN,NaN,NaN,NaN,NaN,NaN,2.000000e+00,4.000000e+00,5.397605e-79,5.397605e-79,NaN,NaN,9.0,9.0,1.0,1.0,1.000000e+00,1.000000e+00,9.0,NaN,NaN,2173.0,373.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,NaN
3,1.0,1.0,b'01142015',b'01',b'14',b'2015',1100.0,2.015000e+09,2.015000e+09,1.0,1.0,NaN,1.0,2.0,NaN,3.0,1.000000e+00,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,30.0,30.0,30.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,NaN,2.0,1.0,2.0,1.0,1.0,2.0,3.0,NaN,2.0,1.0,4.0,1.0,2.0,NaN,1.0,2.0,8.0,1.0,8.0,2.0,180.0,507.0,NaN,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,NaN,NaN,NaN,3.0,888.0,NaN,NaN,NaN,555.0,101.0,555.0,301.0,301.0,201.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,888.0,1.0,1.0,1.0,8.0,1.0,1.0,777777.0,5.0,1.0,9.0,NaN,NaN,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,2.0,1.0,1.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',4.0,7.0,NaN,NaN,NaN,97.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,b'',b'',3.0,11011.0,28.78156,3.0,86.344681,NaN,NaN,NaN,NaN,1.0,0.614125,341.384853,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,3.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,9.0,1.0,63.0,5.0,67.0,170.0,8165.0,2819.0,3.0,2.0,2.0,2.0,5.0,4.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,5.397605e-79,100.0,5.397605e-79,3.0,3.0,14.0,5.397605e-79,5.397605e-79,1.000000e+00,1.000000e+00,100.0,20.0,1.0,2.0,1.0,1.0,5.397605e-79,5.397605e-79,2.0,NaN,NaN,2469.0,423.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.397605e-79,5.397605e-79,NaN,NaN,NaN,NaN,NaN,NaN,4.0,2.0,3.0,3.0,2.0,2.0,4.0,2.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,9.0
4,1.0,1.0,b'01142015',b'01',b'14',b'2015',1100.0,2.015000e+09,2.015000e+09,1.0,1.0,NaN,1.0,2.0,NaN,2.0,1.000000e+00,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,20.0,88.0,30.0,1.0,1.0,2.0,1.0,3.0,NaN,1.0,1.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,1.0,2.0,2.0,3.0,NaN,2.0,1.0,5.0,1.0,2.0,NaN,2.0,2.0,8.0,88.0,77.0,1.0,142.0,504.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,3.0,888.0,NaN,NaN,NaN,777.0,102.0,203.0,204.0,310.0,320.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,888.0,1.0,1.0,1.0,7.0,1.0,2.0,NaN,NaN,1.0,1.0,777777.0,1.0,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,1.0,777.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,2.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',5.0,5.0,NaN,NaN,NaN,45.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,b'',b'',3.0,11011.0,28.78156,2.0,57.563120,NaN,NaN,NaN,NaN,9.0,NaN,258.682223,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,3.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,9.0,1.0,61.0,5.0,64.0,163.0,6441.0,2437.0,2.0,1.0,1.0,3.0,9.0,4.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,NaN,200.0,4.300000e+01,57.0,33.0,67.0,1.000000e+00,5.397605e-79,5.397605e-79,1.000000e+00,NaN,200.0,9.0,1.0,1.0,1.0,1.000000e+00,5.397605e-79,2.0,NaN,NaN,2543.0,436.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.397605e-79,5.397605e-79,NaN,NaN,NaN,NaN,NaN,NaN,4.0,2.0,3.0,3.0,2.0,2.0,4.0,2.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,1.0

In [ ]:
data = data[
    [
        'DIABETE3',
        '_RFHYPE5',
        'TOLDHI2',
        '_CHOLCHK',
        '_BMI5',
        'SMOKE100',
        'CVDSTRK3',
        '_MICHD',
        '_TOTINDA',
        '_FRTLT1',
        '_VEGLT1',
        '_RFDRHV5',
        'HLTHPLN1',
        'MEDCOST',
        'GENHLTH',
        'MENTHLTH',
        'PHYSHLTH',
        'DIFFWALK',
        'SEX',
        '_AGEG5YR',
        'EDUCA',
        'INCOME2',
        '_RACE_G1',
        '_STATE'
    ]
]

In [ ]:
data.shape

(441456, 24)

### Data Preprocessing

In [ ]:
data['_RFHYPE5'] = data['_RFHYPE5'].replace({1: 0, 2: 1})
data = data[data._RFHYPE5 != 9]

data['TOLDHI2'] = data['TOLDHI2'].replace({2: 0})
data = data[data.TOLDHI2 != 7]
data = data[data.TOLDHI2 != 9]

data['_CHOLCHK'] = data['_CHOLCHK'].replace({3: 0, 2: 0})
data = data[data._CHOLCHK != 9]

data['_BMI5'] = data['_BMI5'].div(100).round(0)

data['SMOKE100'] = data['SMOKE100'].replace({2: 0})
data = data[data.SMOKE100 != 7]
data = data[data.SMOKE100 != 9]

data['CVDSTRK3'] = data['CVDSTRK3'].replace({2: 0})
data = data[data.CVDSTRK3 != 7]
data = data[data.CVDSTRK3 != 9]

data['_MICHD'] = data['_MICHD'].replace({2: 0})

data['_TOTINDA'] = data['_TOTINDA'].replace({2: 0})
data = data[data._TOTINDA != 9]

data['_FRTLT1'] = data['_FRTLT1'].replace({2: 0})
data = data[data._FRTLT1 != 9]

data['_VEGLT1'] = data['_VEGLT1'].replace({2: 0})
data = data[data._VEGLT1 != 9]

data['_RFDRHV5'] = data['_RFDRHV5'].replace({1: 0, 2: 1})
data = data[data._RFDRHV5 != 9]


data['HLTHPLN1'] = data['HLTHPLN1'].replace({2: 0})
data = data[data.HLTHPLN1 != 7]
data = data[data.HLTHPLN1 != 9]

data['MEDCOST'] = data['MEDCOST'].replace({2: 0})
data = data[data.MEDCOST != 7]
data = data[data.MEDCOST != 9]

data = data[data.GENHLTH != 7]
data = data[data.GENHLTH != 9]

data['MENTHLTH'] = data['MENTHLTH'].replace({88: 0})
data = data[data.MENTHLTH != 77]
data = data[data.MENTHLTH != 99]

data['PHYSHLTH'] = data['PHYSHLTH'].replace({88: 0})
data = data[data.PHYSHLTH != 77]
data = data[data.PHYSHLTH != 99]

data['DIFFWALK'] = data['DIFFWALK'].replace({2: 0})
data = data[data.DIFFWALK != 7]
data = data[data.DIFFWALK != 9]

# Original: 1 - Male  2 - Female
data['SEX'] = data['SEX'].replace({2: 0})

data = data[data._AGEG5YR != 14]

data = data[data.EDUCA != 9]

data = data[data.INCOME2 != 77]
data = data[data.INCOME2 != 99]

data = data[data._RACE_G1 != 9]

data = data[data._STATE != 99]

<ipython-input-9-5abbdcc1cf7c>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['TOLDHI2'] = data['TOLDHI2'].replace({2: 0})
<ipython-input-9-5abbdcc1cf7c>:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['HLTHPLN1'] = data['HLTHPLN1'].replace({2: 0})
<ipython-input-9-5abbdcc1cf7c>:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['PHYSHLTH'] = data['PHYSHLTH'].replace({88: 0})

### Binarizing Target Variable

In [ ]:
data['DIABETE3'].value_counts()

DIABETE3
3.0    251882
1.0     37955
4.0      5098
2.0      2507
7.0       231
9.0        20
Name: count, dtype: int64

In [ ]:
data = data[data.DIABETE3 != 7]
data = data[data.DIABETE3 != 9]

data['DIABETE3'] = data['DIABETE3'].replace({2: 0, 3: 0, 4: 1})

In [ ]:
data['DIABETE3'].value_counts()

DIABETE3
0.0    254389
1.0     43053
Name: count, dtype: int64

### Cleaning null values by removing rows with any null value

In [ ]:
data.isnull().sum()

DIABETE3        3
_RFHYPE5        0
TOLDHI2     32186
_CHOLCHK        0
_BMI5       11782
SMOKE100        1
CVDSTRK3        0
_MICHD       1694
_TOTINDA        0
_FRTLT1         0
_VEGLT1         0
_RFDRHV5        0
HLTHPLN1        0
MEDCOST         1
GENHLTH         1
MENTHLTH        0
PHYSHLTH        0
DIFFWALK        3
SEX             0
_AGEG5YR        0
EDUCA           0
INCOME2         0
_RACE_G1     2732
_STATE          0
dtype: int64

In [ ]:
data.dropna(inplace=True)

In [ ]:
data.isnull().sum()

DIABETE3    0
_RFHYPE5    0
TOLDHI2     0
_CHOLCHK    0
_BMI5       0
SMOKE100    0
CVDSTRK3    0
_MICHD      0
_TOTINDA    0
_FRTLT1     0
_VEGLT1     0
_RFDRHV5    0
HLTHPLN1    0
MEDCOST     0
GENHLTH     0
MENTHLTH    0
PHYSHLTH    0
DIFFWALK    0
SEX         0
_AGEG5YR    0
EDUCA       0
INCOME2     0
_RACE_G1    0
_STATE      0
dtype: int64

In [ ]:
data.shape

(251467, 24)

In [ ]:
data.describe()

,DIABETE3,_RFHYPE5,TOLDHI2,_CHOLCHK,_BMI5,SMOKE100,CVDSTRK3,_MICHD,_TOTINDA,_FRTLT1,_VEGLT1,_RFDRHV5,HLTHPLN1,MEDCOST,GENHLTH,MENTHLTH,PHYSHLTH,DIFFWALK,SEX,_AGEG5YR,EDUCA,INCOME2,_RACE_G1,_STATE
count,251467.000000,251467.000000,251467.000000,251467.000000,251467.000000,251467.000000,251467.000000,251467.000000,251467.000000,251467.000000,251467.000000,251467.000000,251467.000000,251467.000000,251467.00000,251467.000000,251467.000000,251467.000000,251467.000000,251467.000000,251467.000000,251467.000000,251467.000000,251467.000000
mean,0.157345,0.428915,0.424163,0.962842,28.380841,0.442837,0.040467,0.094008,0.756668,0.634155,0.811474,0.056238,0.951250,0.083796,2.51031,3.180425,4.231772,0.167962,0.439429,8.031050,5.051180,6.056715,1.398486,30.093857
std,0.364126,0.494922,0.494216,0.189149,6.606212,0.496723,0.197051,0.291841,0.429095,0.481667,0.391132,0.230381,0.215345,0.277083,1.06765,7.406515,8.706607,0.373834,0.496319,3.053821,0.984989,2.069854,0.910966,16.042699
min,0.000000,0.000000,0.000000,0.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.00000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,0.000000,0.000000,0.000000,1.000000,24.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,2.00000,0.000000,0.000000,0.000000,0.000000,6.000000,4.000000,5.000000,1.000000,18.000000
50%,0.000000,0.000000,0.000000,1.000000,27.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,2.00000,0.000000,0.000000,0.000000,0.000000,8.000000,5.000000,7.000000,1.000000,29.000000
75%,0.000000,1.000000,1.000000,1.000000,31.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,3.00000,2.000000,3.000000,0.000000,1.000000,10.000000,6.000000,8.000000,1.000000,44.000000
max,1.000000,1.000000,1.000000,1.000000,98.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,5.00000,30.000000,30.000000,1.000000,1.000000,13.000000,6.000000,8.000000,5.000000,72.000000

### Renaming

In [ ]:
data = data.rename(columns={
    'DIABETE3': 'Diabetes',
    '_RFHYPE5': 'PressAlta',
    'TOLDHI2': 'ColestAlto',
    '_CHOLCHK': 'VerifColest',
    '_BMI5': 'IMC',
    'SMOKE100': 'Fumante',
    'CVDSTRK3': 'Derrame',
    '_MICHD': 'DoencaCardiaca',
    '_TOTINDA': 'AtivFisica',
    '_FRTLT1': 'Frutas',
    '_VEGLT1': 'Vegetais',
    '_RFDRHV5': 'ConsumoAlcool',
    'HLTHPLN1': 'AssistMedica',
    'MEDCOST': 'SemMedicoCusto',
    'GENHLTH': 'SaudeGeral',
    'MENTHLTH': 'SaudeMental',
    'PHYSHLTH': 'SaudeFisica',
    'DIFFWALK': 'DificCaminhar',
    'SEX': 'Sexo',
    '_AGEG5YR': 'Idade',
    'EDUCA': 'Escolaridade',
    'INCOME2': 'Renda',
    '_RACE_G1': 'Etnia',
    '_STATE': 'Estado'
})

In [ ]:
data.corr()['Diabetes'].sort_values(ascending=False)

Diabetes          1.000000
SaudeGeral        0.300835
PressAlta         0.270140
IMC               0.223740
DificCaminhar     0.222354
ColestAlto        0.210530
Idade             0.185608
DoencaCardiaca    0.176943
SaudeFisica       0.174895
Derrame           0.104742
SaudeMental       0.074662
VerifColest       0.067567
Fumante           0.062381
Etnia             0.055796
SemMedicoCusto    0.038525
Sexo              0.029598
AssistMedica      0.013992
Estado            0.006285
Frutas           -0.042209
ConsumoAlcool    -0.056894
Vegetais         -0.059211
AtivFisica       -0.121508
Escolaridade     -0.131466
Renda            -0.173015
Name: Diabetes, dtype: float64

In [ ]:
for coluna in data.columns:
  print(f"{data[coluna].value_counts()}")
  print("\n")

Diabetes
0.0    211900
1.0     39567
Name: count, dtype: int64


PressAlta
0.0    143609
1.0    107858
Name: count, dtype: int64


ColestAlto
0.0    144804
1.0    106663
Name: count, dtype: int64


VerifColest
1.0    242123
0.0      9344
Name: count, dtype: int64


IMC
27.0    24365
26.0    20367
24.0    19380
25.0    17011
28.0    16396
        ...
85.0        1
86.0        1
91.0        1
90.0        1
78.0        1
Name: count, Length: 84, dtype: int64


Fumante
0.0    140108
1.0    111359
Name: count, dtype: int64


Derrame
0.0    241291
1.0     10176
Name: count, dtype: int64


DoencaCardiaca
0.0    227827
1.0     23640
Name: count, dtype: int64


AtivFisica
1.0    190277
0.0     61190
Name: count, dtype: int64


Frutas
1.0    159469
0.0     91998
Name: count, dtype: int64


Vegetais
1.0    204059
0.0     47408
Name: count, dtype: int64


ConsumoAlcool
0.0    237325
1.0     14142
Name: count, dtype: int64


AssistMedica
1.0    239208
0.0     12259
Name: count, dtype: int64


SemMedicoCusto
0.0    230395
1.0     21072
Name: count, dtype: int64


SaudeGeral
2.0    88443
3.0    74980
1.0    44890
4.0    31226
5.0    11928
Name: count, dtype: int64


SaudeMental
0.0     174156
2.0      12962
30.0     11959
5.0       8958
1.0       8459
3.0       7331
10.0      6313
15.0      5448
4.0       3767
20.0      3329
7.0       3071
25.0      1173
14.0      1159
6.0        983
8.0        627
12.0       388
28.0       323
21.0       224
29.0       156
18.0        97
9.0         89
16.0        88
27.0        78
22.0        62
17.0        54
26.0        45
11.0        41
13.0        41
23.0        38
24.0        33
19.0        15
Name: count, dtype: int64


SaudeFisica
0.0     158737
30.0     19165
2.0      14650
1.0      11298
3.0       8426
5.0       7545
10.0      5537
15.0      4866
4.0       4503
7.0       4503
20.0      3238
14.0      2564
25.0      1318
6.0       1316
8.0        802
21.0       656
12.0       572
28.0       517
29.0       211
9.0        177
18.0       148
16.0       110
27.0        97
17.0        96
24.0        72
22.0        70
26.0        69
13.0        66
11.0        60
23.0        56
19.0        22
Name: count, dtype: int64


DificCaminhar
0.0    209230
1.0     42237
Name: count, dtype: int64


Sexo
0.0    140965
1.0    110502
Name: count, dtype: int64


Idade
9.0     32959
10.0    31903
8.0     30562
7.0     26092
11.0    23324
6.0     19664
13.0    17190
5.0     16024
12.0    15830
4.0     13702
3.0     11042
2.0      7536
1.0      5639
Name: count, dtype: int64


Escolaridade
6.0    106446
5.0     69259
4.0     62265
3.0      9354
2.0      3969
1.0       174
Name: count, dtype: int64


Renda
8.0    89694
7.0    42899
6.0    36145
5.0    25643
4.0    19914
3.0    15822
2.0    11662
1.0     9688
Name: count, dtype: int64


Etnia
1.0    201886
2.0     18001
3.0     17068
4.0      9979
5.0      4533
Name: count, dtype: int64


Estado
20.0    12584
31.0    10576
27.0     9770
53.0     9387
48.0     7656
8.0      7272
24.0     7174
36.0     7021
9.0      6890
6.0      6850
39.0     6691
45.0     6598
34.0     6309
49.0     6237
23.0     6165
12.0     5642
26.0     5454
51.0     5285
25.0     4659
15.0     4650
1.0      4373
46.0     4249
4.0      4239
40.0     4155
29.0     4111
33.0     4078
21.0     3966
35.0     3903
55.0     3898
50.0     3860
17.0     3806
19.0     3687
18.0     3591
37.0     3557
16.0     3504
44.0     3444
28.0     3432
30.0     3420
54.0     3338
72.0     3310
42.0     3289
47.0     3250
56.0     3077
38.0     3025
41.0     2879
5.0      2825
13.0     2615
22.0     2487
11.0     2264
10.0     2195
2.0      2154
32.0     1610
66.0     1006
Name: count, dtype: int64

### Exporting the new dataset

In [ ]:
data.to_csv('dados_limpos2015.csv', index=False)